language: python
python:
  - 3.5
  - 3.6
script:
  - pip install nose coverage
  - nosetests ./
    --with-coverage --cover-package=riff --cover-html --cover-erase
    #--with-doctest --doctest-extension=md --doctest-options=+ELLIPSIS
  - pip install pycodestyle
  - pycodestyle ./ --show-source --select=E,W
after_success:
  - pip install coveralls
  - coveralls
